const articles = [
  {
    title: "Steve Rogers",
    categories: [
  "Characters",
  "Avengers Emergency Response Squad (Earth-616)/Members",
  "Avengers Unity Division (Earth-616)/Members",
  "Avengers (Earth-616)/Members",
  "Strategic Homeland Intervention, Enforcement and Logistics Division (Earth-616)/Members",
  "Illuminati (Earth-616)/Members",
  "Invaders (Earth-616)/Members",
  "United States Army (Earth-616)/Members",
  "Project Rebirth (Earth-616)/Members",
  "Secret Avengers (Black Ops Unit) (Earth-616)/Members",
  "Mighty (Earth-616)/Members",
  "Captain America Corps (Earth-616)/Members",
  "Secret Avengers (Civil War) (Earth-616)/Members",
  "New Avengers (Earth-616)/Members",
  "Avengers (Multiverse)/Members",
  "Avengers (Heroes Reborn) (Earth-616)/Members",
  "Secret Defenders (Earth-616)/Members",
  "Specialized Unit, Enhanced Soldiers (Earth-616)/Members",
  "Hive (Symbiotes) (Earth-616)/Members",
  "Jotunheim Strikeforce (Earth-616)/Members",
  "Queen's Vengeance (Earth-398)/Members",
  "Hosts of Carnage Symbiote",
  "Single Characters",
  "Male Characters",
  "Height 6 ft. 2 in. (1.88 m)",
  "Weight 220-239 lbs (99.79-108.86 kg)",
  "Blue Eyes",
  "Blond Hair",
  "Humans (Homo sapiens)",
  "Mutates",
  "Super-Soldiers",
  "Living Characters",
  "Formerly Deceased",
  "Earth-616/Characters",
  "Killed by Victor von Doom (Earth-616)",
  "Killed by Thanos (Earth-616)",
  "Killed by Michael Korvac (Earth-691)",
  "Killed by Nathaniel Richards (Kang) (Earth-6311)",
  "Killed by Sharon Carter (Earth-616)",
  "Killed by Progenitor (Celestial) (Multiverse)",
  "Secret Wars (1984 Event) casualties",
  "Infinity Gauntlet (Event) casualties",
  "Korvac Saga casualties",
  "Civil War casualties",
  "Time Runs Out casualties",
  "A.X.E.: Judgment Day casualties",
  "Public Identity Characters",
  "Americans",
  "Leaders",
  "Police Officers",
  "Adventurers",
  "Teachers",
  "Military Personnel",
  "Joe Simon/Creator",
  "Jack Kirby/Creator",
  "1940 Character Debuts",
  "Disease Immunity",
  "Regeneration",
  "Artificially Enhanced Intelligence",
  "Advanced Longevity",
  "Superhuman Strength",
  "Superhuman Stamina",
  "Superhuman Agility",
  "Superhuman Reflexes",
  "Superhuman Speed",
  "Superhuman Senses",
  "Superhuman Durability",
  "Wallcrawling",
  "Organic Webbing",
  "Strategists",
  "Martial Arts",
  "Shield Fighting",
  "Acrobats",
  "Gymnasts",
  "Shooting",
  "Fencing",
  "Weapons Expert",
  "Thrown Weapon Mastery",
  "Computer Hacking Skills",
  "Pilots",
  "Multilingual",
  "Speakers of English",
  "Speakers of Spanish",
  "Speakers of Japanese",
  "Speakers of German",
  "Speakers of Russian",
  "Speakers of French",
  "Speakers of Italian",
  "Steven Rogers (Earth-616)/Quotes",
  "Power Grid/Intelligence/Learned",
  "Power Grid/Strength/Peak Human",
  "Power Grid/Speed/Normal",
  "Power Grid/Durability/Enhanced",
  "Power Grid/Energy Projection/None",
  "Power Grid/Fighting Skills/Master: Several Forms of Combat",
  "Worthy of Mjolnir",
  "WWII Characters",
  "Rogers Family",
  "Painters",
  "Abraham Erskine Experiment",
  "Power Level 8",
  "Doctor Octopus Experiment",
  "Secret Wars (1984 Event) participants",
  "Time Travelers",
  "Korvac Saga participants",
  "Government Agents",
  "Destiny War Participants",
  "Paladin-Plus Clearance",
  "Time-Looped",
  "Spider-Virus Victims",
  "Collector's Museum",
  "S.H.I.E.L.D. Directors",
  "Shared Identities: Successors",
  "Ebony Blade User",
  "Infinity Gauntlet wielders",
  "Floating Super-Hero Poker Game participants",
  "Damnation participants",
  "Reincarnation",
  "Lupine Form",
  "Gestalt Characters",
  "Former Werewolves",
  "Libra (Astrological Sign)"
    ]
  },
  {
    title: "Tony Stark",
    categories: [
  "Characters",
  "Avengers (Earth-616)/Members",
  "West Coast Avengers (Earth-616)/Members",
  "Hellfire Club (Earth-616)/Members",
  "Alcoholics Anonymous (Earth-616)/Members",
  "Space Friends (Earth-616)/Members",
  "Darkhold Defiled (Earth-616)/Members",
  "A.I. Army (Earth-616)/Members",
  "Stark Unlimited (Earth-616)/Members",
  "Stark Industries (Earth-616)/Members",
  "Red Team (Earth-15513)/Members",
  "Avengers (Heroes Reborn) (Earth-616)/Members",
  "Illuminati (Earth-616)/Members",
  "Axis (Avengers) (Earth-616)/Members",
  "Stark Resilient (Earth-616)/Members",
  "Strategic Homeland Intervention, Enforcement and Logistics Division (Earth-616)/Members",
  "Guardians of the Galaxy (Earth-616)/Members",
  "50-State Initiative (Earth-616)/Members",
  "New Avengers (Earth-616)/Members",
  "Mighty Avengers (Initiative) (Earth-616)/Members",
  "Mighty Avengers (Pym) (Earth-616)/Members",
  "Maria Stark Foundation (Earth-616)/Members",
  "Stark Solutions (Earth-616)/Members",
  "Force Works (Earth-616)/Members",
  "United States Department of Defense (Earth-616)/Members",
  "Mighty (Earth-616)/Members",
  "Knights of the Atomic Round Table (Earth-616)/Members",
  "Damage Control (Earth-616)/Members",
  "Imperio Techworks (Earth-616)/Members",
  "Queen's Vengeance (Earth-398)/Members",
  "Hosts of Extrembiote Symbiote",
  "Single Characters",
  "Male Characters",
  "Height 6 ft. 1 in. (1.85 m)",
  "Height 6 ft. 6 in. (1.98 m)",
  "Weight 220-239 lbs (99.79-108.86 kg)",
  "Weight 400-499 lbs (181.44-226.8 kg)",
  "Blue Eyes",
  "Black Hair",
  "Cyborgs",
  "Humans (Homo sapiens)",
  "Living Characters",
  "Formerly Deceased",
  "Earth-616/Characters",
  "Killed by En Dwi Gast (Earth-616)",
  "Killed by Terraxia (Earth-616)",
  "Killed by Nathaniel Richards (Kang) (Earth-6311)",
  "Infinity Gauntlet (Event) casualties",
  "Crossing casualties",
  "Time Runs Out casualties",
  "Self-sacrifice",
  "Public Identity Characters",
  "Multiple Citizenship",
  "Americans",
  "Bulgarians",
  "Businesspeople",
  "Mechanics",
  "Adventurers",
  "Secretaries",
  "Engineers",
  "Inventors",
  "Stan Lee/Creator",
  "Larry Lieber/Creator",
  "Don Heck/Creator",
  "Jack Kirby/Creator",
  "1962 Character Debuts",
  "Speakers of English",
  "Speakers of Japanese",
  "Speakers of Chinese",
  "Speakers of Spanish",
  "Speakers of French",
  "Speakers of Russian",
  "Speakers of Korean",
  "Speakers of Urdu",
  "Anthony Stark (Earth-616)/Quotes",
  "Power Grid/Intelligence/Super-Genius",
  "Power Grid/Strength/Normal",
  "Power Grid/Strength/Superhuman (75-100 ton)",
  "Power Grid/Speed/Normal",
  "Power Grid/Speed/Supersonic",
  "Power Grid/Durability/Weak",
  "Power Grid/Durability/Superhuman",
  "Power Grid/Energy Projection/None",
  "Power Grid/Energy Projection/Multiple Types",
  "Power Grid/Fighting Skills/Experienced Fighter",
  "Alcoholism",
  "Armor Users",
  "Artificial Intelligences",
  "Artificially Enhanced Intelligence",
  "Atheist Characters",
  "Blood Type A+",
  "Cambridge University Student",
  "Collector's Museum",
  "Computer Hacking Skills",
  "Concussive Blasts",
  "Consciousness Transferred",
  "Death by accident",
  "Depression",
  "Doctor Octopus Experiment",
  "Extremis",
  "Fear Itself",
  "Flight",
  "Floating Super-Hero Poker Game participants",
  "Gemini (Astrological Sign)",
  "Gestalt Characters",
  "Infinity Gauntlet wielders",
  "Interdimensional Travelers",
  "Korvac Saga participants",
  "M.I.T. Student",
  "Millionaires",
  "Multilingual",
  "Multiple forms of Energy Projection",
  "Physicists",
  "Plasma Generation",
  "Power Level 9",
  "Regeneration",
  "Robotics",
  "S.H.I.E.L.D. Directors",
  "Scientists",
  "Shared Identities: Successors",
  "Stark Family",
  "Strength Class 100",
  "Super-Genius Intelligence",
  "Superhuman (75-100 ton) Strength",
  "Superhuman Durability",
  "Superhuman Strength",
  "Supersonic Speed",
  "Technopaths",
  "Doctors",
  "Three Doctorates",
  "Time Travelers",
  "Trained by Captain America",
  "Trained by Shang-Chi",
  "Vietnam War Characters",
  "Virtual Reality Users",
  "Warp Speed",
  "Leaders",
  "Nanobots",
  "Power Cosmic",
  "Billionaires",
  "Martial Arts"
    ]
  },
 {
    title: "Captain Marvel",
categories = [
  "Characters",
  "Killed by Michael Rossi (Earth-616)",
  "Killed by Progenitor (Celestial) (Multiverse)",
  "Killed by Thanos (Earth-616)",
  "A.X.E.: Judgment Day casualties",
  "Public Identity Characters",
  "Americans",
  "Intelligence Agents",
  "Leaders",
  "Military Personnel",
  "Adventurers",
  "Writers",
  "Pilots",
  "Roy Thomas/Creator",
  "Gene Colan/Creator",
  "1967 Character Debuts",
  "Flight",
  "Danger Sense",
  "Superhuman Strength",
  "Superhuman Durability",
  "Superhuman Stamina",
  "Superhuman Agility",
  "Superhuman Reflexes",
  "Healing",
  "Energy Absorption",
  "Energy Manipulation",
  "Light Generation",
  "Self Sustenance",
  "Size Increase",
  "Regeneration",
  "Speakers of English",
  "Speakers of Russian",
  "Speakers of Chinese",
  "Speakers of Arabic",
  "Speakers of French",
  "Carol Danvers (Earth-616)/Quotes",
  "Power Grid/Intelligence/Learned",
  "Power Grid/Strength/Superhuman (25-75 ton)",
  "Power Grid/Speed/Supersonic",
  "Power Grid/Durability/Superhuman",
  "Power Grid/Energy Projection/Single Type: Long Range",
  "Power Grid/Fighting Skills/Experienced Fighter",
  "Government Agents",
  "Human/Kree Hybrids",
  "Psyche-Magnitron Enhanced",
  "Kree Experiment",
  "Danvers Family",
  "Strength Class 50",
  "Strength Class 90",
  "Strength Class 100",
  "Alcoholism",
  "Multilingual",
  "Power Level 8",
  "Avengers Clearance Alpha",
  "Korvac Saga participants",
  "Astronauts",
  "Secret Wars (2015 Event) participants",
  "War in Afghanistan Characters",
  "Interdimensional Travelers",
  "Floating Super-Hero Poker Game participants",
  "Damnation participants",
  "Reality Stone wielders",
  "Consciousness Transferred",
  "Gestalt Characters",
  "Optic Blasts",
  "Cancer (disease)",
  "Brood-infected"
]
  },
  {
    title: "Thor",
 categories = [
  "Characters",
  "Thor Corps (Earth-616)/Members",
  "Avengers (Earth-616)/Members",
  "Heralds of Galactus (Earth-616)/Members",
  "Avengers (Hydra) (Earth-616)/Members",
  "Thor Corps (Earth-15513)/Members",
  "New Avengers (A.I.M.) (Earth-616)/Members",
  "Avengers Unity Division (Earth-616)/Members",
  "Axis (Avengers) (Earth-616)/Members",
  "Avengers (Heroes Reborn) (Earth-616)/Members",
  "Avengers (1,000 AD) (Earth-616)/Members",
  "League of Realms (Earth-616)/Members",
  "God Squad (Earth-616)/Members",
  "Council of Godheads (Earth-616)/Members",
  "Queen's Vengeance (Earth-398)/Members",
  "Circus of Crime (Earth-616)/Members",
  "Godpack (Earth-616)/Members",
  "Hosts of All-Black Symbiote",
  "Single Characters",
  "Male Characters",
  "Height 6 ft. 6 in. (1.98 m)",
  "Height 5 ft. 9 in. (1.75 m)",
  "Weight 600-699 lbs (272.16-317.51 kg)",
  "Weight 140-159 lbs (63.5-72.57 kg)",
  "Blue Eyes",
  "Formerly No Visible Irises or Pupils",
  "Formerly Yellow Eyes",
  "Formerly White Eyeballs",
  "Formerly Green Eyeballs",
  "Blond Hair",
  "Formerly White Hair",
  "Formerly Blue Skin",
  "Formerly Green Skin",
  "Claws",
  "Cathexis Ray Exposure",
  "Asgardians",
  "Deities",
  "Elder Gods",
  "Gamma Ray Exposure",
  "Humans (Homo sapiens)",
  "Mutates",
  "Virtual Immortals",
  "Living Characters",
  "Formerly Deceased",
  "Earth-616/Characters",
  "Killed by Victor von Doom (Earth-616)",
  "Killed by Laufey (Earth-616)",
  "Killed by En Dwi Gast (Earth-616)",
  "Killed by Cul Borson (Earth-616)",
  "Killed by All-Black (Symbiote) (Earth-616)",
  "Killed by Progenitor (Celestial) (Multiverse)",
  "Killed by Thanos (Earth-616)",
  "Killed by Loki Laufeyson (Ikol) (Earth-616)",
  "Secret Wars (1984 Event) casualties",
  "Fear Itself casualties",
  "Time Runs Out casualties",
  "A.X.E.: Judgment Day casualties",
  "No Dual Identity Characters",
  "Sky Fathers",
  "Monarchs",
  "Physicians",
  "Adventurers",
  "Construction worker",
  "Don Rico/Creator",
  "Hy Rosen/Creator",
  "Stan Lee/Creator",
  "Jack Kirby/Creator",
  "Larry Lieber/Creator",
  "1950 Character Debuts",
  "Elder God/Asgardian Hybrids",
  "Superhuman Strength",
  "Invulnerability",
  "Disease Immunity",
  "Toxic Immunity",
  "Cold Immunity",
  "Superhuman Speed",
  "Superhuman Stamina",
  "Superhuman Agility",
  "Superhuman Reflexes",
  "Energy Manipulation",
  "Energy Projection",
  "Weather Manipulation",
  "Thunder Deities",
  "Precipitation Manipulation",
  "Wind Manipulation",
  "Electricity Manipulation",
  "Water Manipulation",
  "Ice Manipulation",
  "Electricity Generation",
  "Superhuman Senses",
  "Superhuman Vision",
  "Superhuman Hearing",
  "Regeneration",
  "Wind Breath",
  "Flight",
  "Telepathy",
  "Teleportation",
  "Force Field",
  "Portal Creation",
  "Time Manipulation",
  "Healing",
  "Power Absorption",
  "Fire Generation",
  "Fire Manipulation",
  "Geokinesis",
  "Magicians",
  "Precognition",
  "Power Cosmic",
  "Plant Manipulation",
  "Telepathic Immunity",
  "Energy Absorption",
  "Magnetism Manipulation",
  "Matter Manipulation",
  "Transmutation",
  "Electromagnetic Spectrum Manipulation",
  "Energy Senses",
  "Interdimensional Teleportation",
  "Remote Teleportation",
  "Soul Manipulation",
  "Life-Force Absorption",
  "Time Traveling",
  "Resurrection",
  "1962 Character Debuts",
  "Thor Odinson (Earth-616)/Quotes",
  "Power Grid/Intelligence/Normal",
  "Power Grid/Strength/Incalculable",
  "Power Grid/Speed/Warp",
  "Power Grid/Durability/Superhuman",
  "Power Grid/Energy Projection/Multiple Types",
  "Power Grid/Fighting Skills/Experienced Fighter",
  "Worthy of Mjolnir",
  "Fencing",
  "One Arm",
  "One Eye",
  "Doctor Octopus Experiment",
  "Secret Wars (1984 Event) participants",
  "Korvac Saga participants",
  "Time Travelers",
  "Interdimensional Travelers",
  "Diplomatic Immunity",
  "Dynamokinesis",
  "Collector's Museum",
  "Gaea Family",
  "Thor Family",
  "Odin Family",
  "Frigga Family",
  "Trojan War Characters",
  "Secret Wars (2015 Event) participants",
  "Power Stone wielders",
  "Time Stone wielders",
  "Mythological Figures",
  "Brood-infected",
  "Avatar Form",
  "Gestalt Characters",
  "Characters Displaced to Earth-15513",
  "Strategists",
  "Dimensional Rulers",
  "Messiahs",
  "Billionaires",
  "Lightning Deities",
  "Storm Deities",
  "Asgard Monarchs",
  "Former Deities",
  "Erased History"
]
  },
  {
    title: "Black Panther",
    categories: [
  "Characters",
  "Avengers (Earth-616)/Members",
  "Taifa Ngao (Earth-616)/Members",
  "Panther Cult (Earth-616)/Members",
  "Congress of Worlds (Earth-616)/Members",
  "Maroons (Earth-616)/Members",
  "Galactic Union (Earth-616)/Members",
  "Structure (Vampires) (Earth-616)/Members",
  "Crew (Earth-616)/Members",
  "Ultimates (Earth-616)/Members",
  "Nameless (Intergalactic Empire of Wakanda) (Earth-616)/Members",
  "Alpha Flight's Board of Governors (Earth-616)/Members",
  "Illuminati (Earth-616)/Members",
  "Fantastic Four (Earth-616)/Members",
  "Fantastic Force (Earth-616)/Members",
  "Defenders (Earth-616)/Members",
  "Secret Avengers (Civil War) (Earth-616)/Members",
  "Queen's Vengeance (Earth-398)/Members",
  "Hosts of Phoenix Force",
  "Hosts of Spirits of Vengeance",
  "Hosts of Shadow King",
  "Hosts of Varnae",
  "Single Characters",
  "Male Characters",
  "Height 6 ft. 0 in. (1.83 m)",
  "Weight 200-219 lbs (90.72-99.79 kg)",
  "Brown Eyes",
  "Amber Eyes",
  "Green Eyes",
  "Black Hair",
  "Claws",
  "Humans (Homo sapiens)",
  "Mutates",
  "Living Characters",
  "Formerly Deceased",
  "Earth-616/Characters",
  "Killed by Michael Korvac (Earth-691)",
  "Korvac Saga casualties",
  "Public Identity Characters",
  "Wakandans",
  "Vigilantes",
  "Monarchs",
  "Adventurers",
  "Teachers",
  "Scientists",
  "Stan Lee/Creator",
  "Jack Kirby/Creator",
  "1966 Character Debuts",
  "Superhuman Senses",
  "Telescopic Vision",
  "Ultraviolet Vision",
  "Infrared Vision",
  "Night Vision",
  "Superhuman Hearing",
  "Superhuman Smelling",
  "Superhuman Taste",
  "Necromancy",
  "Energy Construct Creation",
  "Cosmic Awareness",
  "Clairvoyance",
  "Martial Arts",
  "Acrobats",
  "Gymnasts",
  "Shooting",
  "Strategists",
  "Trackers",
  "Multilingual",
  "Inventors",
  "Engineers",
  "Invisibility",
  "Teleportation",
  "T'Challa (Earth-616)/Quotes",
  "Power Grid/Intelligence/Genius",
  "Power Grid/Strength/Peak Human",
  "Power Grid/Speed/Normal",
  "Power Grid/Durability/Enhanced",
  "Power Grid/Energy Projection/Single Type: Short Range",
  "Power Grid/Fighting Skills/Master: Single Form of Combat",
  "Vertical Pupils",
  "Object-Based Powers",
  "Wakandan Royal Family",
  "Munroe Family",
  "Leaders",
  "Ebony Blade User",
  "Weapons Expert",
  "Heart-Shaped Herb",
  "Chemists",
  "Physicists",
  "Robotics",
  "Millionaires",
  "Time Travelers",
  "Korvac Saga participants",
  "Diplomatic Immunity",
  "Oxford University Student",
  "Spider-Virus Victims",
  "Collector's Museum",
  "Armor Users",
  "Secret Wars (2015 Event) participants",
  "Totemic Avatars",
  "Infinity Gauntlet wielders",
  "Damnation participants",
  "Regeneration",
  "Interdimensional Travelers",
  "Souls Sold to Mephisto",
  "Slaves",
  "Fencing",
  "Worthy of Mjolnir",
  "Super-Genius Intelligence",
  "Shadow King",
  "Former Vampires",
  "Billionaires"
    ]
  },
  {
    title: "Vision",
    categories: [
  "Characters",
  "Avengers (Earth-616)/Members",
  "Avengers (Hydra) (Earth-616)/Members",
  "Avengers Unity Division (Earth-616)/Members",
  "Avengers Artificial Intelligence Squad (Earth-616)/Members",
  "Queen's Vengeance (Earth-398)/Members",
  "Avengers (Heroes Reborn) (Earth-616)/Members",
  "West Coast Avengers (Earth-616)/Members",
  "Divorced Characters",
  "Male Characters",
  "Height 6 ft. 3 in. (1.91 m)",
  "Weight 300-399 lbs (136.08-181.44 kg)",
  "Variable Weight",
  "Gold Eyes",
  "No Hair",
  "Red Skin",
  "Cyborgs",
  "Synthezoids",
  "Living Characters",
  "Formerly Deceased",
  "Earth-616/Characters",
  "Killed by Thanos (Earth-616)",
  "Killed by Jennifer Walters (Earth-616)",
  "Killed by Bruce Banner (Earth-616)",
  "Killed by Eric Williams (Earth-616)",
  "Avengers Disassembled casualties",
  "No Dual Identity Characters",
  "Americans",
  "Adventurers",
  "Roy Thomas/Creator",
  "John Buscema/Creator",
  "1968 Character Debuts",
  "Technopaths",
  "Nanobots",
  "Appearance Alteration",
  "Superhuman Hearing",
  "Superhuman Reflexes",
  "Superhuman Stamina",
  "Density Manipulation",
  "Intangibility",
  "Disruption",
  "Possession",
  "Invisibility",
  "Flight",
  "Superhuman Strength",
  "Superhuman Durability",
  "Energy Absorption",
  "Heat Generation",
  "Concussive Blasts",
  "Infrared Generation",
  "Microwave Generation",
  "Janet Van Dyne (Earth-616)/Quotes",
  "Power Grid/Intelligence/Gifted",
  "Power Grid/Strength/Superhuman (25-75 ton)",
  "Power Grid/Speed/Superhuman",
  "Power Grid/Durability/Superhuman",
  "Power Grid/Energy Projection/Multiple Types",
  "Power Grid/Fighting Skills/Some Training",
  "Pym Family",
  "Ultron Family",
  "Vision Family",
  "Maximoff Family",
  "Phineas Horton Experiment",
  "Horton Cells",
  "Artificial Intelligences",
  "Time Travelers",
  "Korvac Saga participants",
  "Korvac Saga casualties",
  "Metal Body",
  "Gestalt Characters",
  "Pym Particles",
  "Infinity Gauntlet (Event) casualties"
    ]
  },
  {
    title: "Black Widow",
    categories: [
  "Advanced Idea Mechanics (Earth-616)/Members",
  "Underground (Secret Empire) (Earth-616)/Members",
  "Red Room (Secret Empire) (Earth-616)/Members",
  "Queen's Vengeance (Earth-398)/Members",
  "Hosts of Sliver Symbiote",
  "Divorced Characters",
  "Female Characters",
  "Height 5 ft. 7 in. (1.7 m)",
  "Weight 120-139 lbs (54.43-63.5 kg)",
  "Green Eyes",
  "Red Hair",
  "Formerly Black Hair",
  "Humans (Homo sapiens)",
  "Mutates",
  "Super-Soldiers",
  "Living Characters",
  "Formerly Deceased",
  "Earth-616/Characters",
  "Killed by Steven Rogers (Earth-61311)",
  "Korvac Saga casualties",
  "Secret Empire (Event) casualties",
  "Self-sacrifice",
  "Public Identity Characters",
  "Multiple Citizenship",
  "Russians",
  "Soviets",
  "Americans",
  "Ballet Dancers",
  "Assassins",
  "Adventurers",
  "Teachers",
  "Fashion Designers",
  "Mercenaries",
  "Stan Lee/Creator",
  "Don Rico/Creator",
  "Don Heck/Creator",
  "1964 Character Debuts",
  "Web-Slinging",
  "Wallcrawling",
  "Memory Absorption",
  "Speakers of Russian",
  "Speakers of English",
  "Speakers of French",
  "Speakers of German",
  "Speakers of Chinese",
  "Speakers of Japanese",
  "Wc fortnite",
  "Natalia Romanova (Earth-616)/Quotes",
  "Power Grid/Intelligence/Learned",
  "Power Grid/Strength/Peak Human",
  "Power Grid/Speed/Normal",
  "Power Grid/Durability/Enhanced",
  "Power Grid/Energy Projection/Single Type: Short Range",
  "Power Grid/Fighting Skills/Master: Several Forms of Combat",
  "Acrobats",
  "Advanced Longevity",
  "Athletic Skills",
  "Computer Hacking Skills",
  "Dancers",
  "Espionage",
  "Fighting Ability - Master of several forms of combat",
  "Government Agents",
  "Gymnasts",
  "Korvac Saga participants",
  "Martial Arts",
  "Multilingual",
  "Orthodox Characters",
  "Peak Human Strength",
  "Power Level 7",
  "Regeneration",
  "Romanov Family",
  "S.H.I.E.L.D. Agents Level 10",
  "Shield Fighting",
  "Shooting",
  "Space Stone wielders",
  "Spies",
  "Strategists",
  "Thrown Weapon Mastery",
  "Trained by Wolverine",
  "Weapons Expert",
  "Disease Immunity"
]
  },
  {
    title: "Peter Quill",
    categories: [
  "Characters",
  "Galactic Union (Earth-616)/Members",
  "Guardians of the Galaxy (Earth-616)/Members",
  "Imperial Kree Army (Earth-616)/Members",
  "Infinity Watch (Earth-616)/Members",
  "National Aeronautics and Space Administration (Earth-616)/Members",
  "Ravagers (Earth-616)/Members",
  "Imperial Guard (Earth-616)/Members",
  "United Front (Earth-616)/Members",
  "Swingin' Stevie Rogers' Band (Earth-61610)/Members",
  "Nova Corps (Earth-616)/Members",
  "Hosts of Symbiotes",
  "Separated Characters",
  "Male Characters",
  "Height 6 ft. 2 in. (1.88 m)",
  "Weight 160-179 lbs (72.57-81.65 kg)",
  "Blue Eyes",
  "Blond Hair",
  "Tattoos",
  "Human/Spartoi Hybrids",
  "Cyborgs",
  "Humans (Homo sapiens)",
  "Hybrids",
  "Spartoi",
  "Living Characters",
  "Formerly Deceased",
  "Earth-616/Characters",
  "Killed by Gamora Zen Whoberi Ben Titan (Earth-7528)",
  "Killed by Groot (Earth-616)",
  "Public Identity Characters",
  "Multiple Citizenship",
  "Americans",
  "Spartax Empire citizens",
  "Vigilantes",
  "Monarchs",
  "Adventurers",
  "Keith Giffen/Creator",
  "Ron Lim/Creator",
  "2004 Character Debuts",
  "Advanced Longevity",
  "Superhuman Durability",
  "Superhuman Reflexes",
  "Regeneration",
  "Apotheosized Mortals",
  "Sun Deities",
  "Gravitational Flight",
  "Light Generation",
  "Telepathic Immunity",
  "Cosmic Awareness",
  "Shooting",
  "Martial Arts",
  "Strategists",
  "Pilots",
  "Peter Quill (Earth-616)/Quotes",
  "Power Grid/Intelligence/Gifted",
  "Power Grid/Strength/Peak Human",
  "Power Grid/Speed/Normal",
  "Power Grid/Durability/Enhanced",
  "Power Grid/Energy Projection/None",
  "Power Grid/Fighting Skills/Experienced Fighter",
  "Quill Family",
  "Bisexual Characters",
  "Astronauts",
  "Leaders",
  "Thieves",
  "Interdimensional Travelers",
  "Secret Wars (2015 Event) participants",
  "Former Deities"
]
  },
  {
    title: "Gamora",
    categories: [
  "Characters",
  "Guardians of the Galaxy (Earth-616)/Members",
  "West Spiral Arm Guardians (Earth-616)/Members",
  "Nova Corps (Earth-616)/Members",
  "Red Team (Earth-15513)/Members",
  "Infinity Watch (Earth-616)/Members",
  "Graces (Earth-616)/Members",
  "United Front (Earth-616)/Members",
  "Selects (Earth-616)/Members",
  "Black Order (Earth-616)/Members",
  "Single Characters",
  "Female Characters",
  "Height 6 ft. 0 in. (1.83 m)",
  "Weight 160-179 lbs (72.57-81.65 kg)",
  "Yellow Eyes",
  "Formerly Green Eyes",
  "Green Hair",
  "Light Green Skin",
  "Zen-Whoberis",
  "Living Characters",
  "Formerly Deceased",
  "Earth-7528/Characters",
  "Killed by Thanos (Earth-616)",
  "Killed by Groot (Earth-616)",
  "No Dual Identity Characters",
  "Assassins",
  "Adventurers",
  "Mercenaries",
  "Jim Starlin/Creator",
  "1975 Character Debuts",
  "Gamora Zen Whoberi Ben Titan (Earth-7528)/Quotes",
  "Power Grid/Intelligence/Learned",
  "Power Grid/Strength/Peak Human",
  "Power Grid/Speed/Speed of Sound",
  "Power Grid/Durability/Enhanced",
  "Power Grid/Energy Projection/None",
  "Power Grid/Fighting Skills/Master: Several Forms of Combat",
  "Martial Arts",
  "Fencing",
  "Regeneration",
  "Superhuman Reflexes",
  "Superhuman Stamina",
  "Gymnasts",
  "War of Kings casualties",
  "Weapons Expert",
  "Acrobats",
  "Black Vortex users",
  "Thanos Family",
  "Strategists",
  "Characters Displaced to Earth-616",
  "Village/City Threat Level",
  "Potential Universal Threat Level",
  "Secret Wars (2015 Event) participants",
  "Thanos Experiment",
  "Interdimensional Travelers",
  "Mind Stone wielders",
  "Power Stone wielders",
  "Soul Stone wielders",
  "Space Stone wielders",
  "Time Stone wielders",
  "Soulless Characters",
  "Superhuman Strength",
  "Superhuman Speed",
  "Superhuman Agility",
  "Superhuman Durability",
  "Thrown Weapon Mastery",
  "Shooting",
  "Armor Users",
  "Time Travelers",
  "Alcoholism",
  "Atheist Characters"
]
  },
  {
    title: "Groot",
    categories: [
  "Characters",
  "West Spiral Arm Guardians (Earth-616)/Members",
  "Galactic Council (Earth-616)/Members",
  "Nova Corps (Earth-616)/Members",
  "Guardians of the Galaxy (Earth-616)/Members",
  "Hosts of Venom Symbiote",
  "Single Characters",
  "Male Characters",
  "Height above 8 ft. (2.44 m)",
  "Weight above 1000 lbs (453.59 kg)",
  "No Visible Irises or Pupils",
  "Yellow Eyeballs",
  "No Hair",
  "Brown Skin",
  "Flora colossi",
  "Wood Body",
  "Living Characters",
  "Formerly Deceased",
  "Earth-616/Characters",
  "Killed by Zeus Panhellenios (Earth-616)",
  "Public Identity Characters",
  "Monarchs",
  "Adventurers",
  "Keith Giffen/Creator",
  "Timothy Green II/Creator",
  "2007 Character Debuts",
  "Regeneration",
  "Size Increase",
  "Stretching",
  "Limited Shape Alteration",
  "Superhuman Strength",
  "Superhuman Durability",
  "Plant Manipulation",
  "Self Sustenance",
  "Healing",
  "Duplication",
  "Flight",
  "Groot (Earth-616)/Quotes",
  "Power Grid/Intelligence/Learned",
  "Power Grid/Strength/Incalculable",
  "Power Grid/Speed/Superhuman",
  "Power Grid/Durability/Regenerative",
  "Power Grid/Energy Projection/Single Type: Short Range",
  "Power Grid/Fighting Skills/Experienced Fighter",
  "Giant Monsters",
  "Collector's Museum",
  "Black Vortex users",
  "Secret Wars (2015 Event) participants",
  "Interdimensional Travelers",
  "Plant Form",
  "Genius Loci",
  "Sentient Planetoids"
]
  },
  {
    title: "Winter Soldier",
    categories: [
  "Characters",
  "New Avengers (Winter Soldier) (Earth-616)/Members",
  "Thunderbolts (Revolution) (Earth-616)/Members",
  "Outer Circle (Earth-616)/Members",
  "Strikeforce (Earth-616)/Members",
  "War Avengers (Earth-616)/Members",
  "Thunderbolts (Earth-616)/Members",
  "Invaders (Earth-616)/Members",
  "Avengers (Earth-616)/Members",
  "Captain America Corps (Earth-616)/Members",
  "New Avengers (Earth-616)/Members",
  "Kid Commandos (Earth-616)/Members",
  "Liberty Legion (Earth-616)/Members",
  "Young Allies (WWII) (Earth-616)/Members",
  "Specialized Unit, Enhanced Soldiers (Earth-616)/Members",
  "Komitet Gosudarstvennoy Bezopasnosti (Earth-616)/Members",
  "Department X (Earth-616)/Members",
  "Black Widow Ops Program (Earth-616)/Members",
  "Legion of the Unliving (Grandmaster) (Earth-616)/Members",
  "Project Rebirth (Earth-616)/Members",
  "United States Army (Earth-616)/Members",
  "Hellhunters (Earth-616)/Members",
  "Single Characters",
  "Male Characters",
  "Height 5 ft. 9 in. (1.75 m)",
  "Weight 260-279 lbs (117.93-127.01 kg)",
  "Brown Eyes",
  "Brown Hair",
  "Cyborgs",
  "Humans (Homo sapiens)",
  "Infinity Formula",
  "Living Characters",
  "Earth-616/Characters",
  "Public Identity Characters",
  "Assassins",
  "Leaders",
  "Military Personnel",
  "Students",
  "Joe Simon/Creator",
  "Jack Kirby/Creator",
  "1940 Character Debuts",
  "Speakers of English",
  "Speakers of Russian",
  "Speakers of German",
  "Speakers of Japanese",
  "Speakers of Chinese",
  "Speakers of French",
  "James Barnes (Earth-616)/Quotes",
  "Power Grid/Intelligence/Normal",
  "Power Grid/Strength/Superhuman (800 lbs-25 ton)",
  "Power Grid/Speed/Normal",
  "Power Grid/Durability/Enhanced",
  "Power Grid/Energy Projection/None",
  "Power Grid/Fighting Skills/Master: All Forms of Combat",
  "One Arm",
  "WWII Characters",
  "Multilingual",
  "Formerly Deceased",
  "Fear Itself",
  "Trained by Captain America",
  "Barnes Family",
  "Weapons Expert",
  "Legally Deceased",
  "Martial Arts",
  "Thrown Weapon Mastery",
  "Shooting",
  "Advanced Longevity",
  "Acrobats",
  "Soviets",
  "Shield Fighting",
  "Superhuman Durability",
  "Superhuman Reflexes",
  "Regeneration",
  "Reincarnation",
  "Spies",
  "Espionage",
  "Avengers (Earth-616)/Images",
  "Heroes Reborn (1996 Event)",
  "Americans",
  "Russians"
]
  },
  {
    title: "Quicksilver",
    categories: [
  "Characters",
  "Avengers (Earth-616)/Members",
  "Avengers Academy (Earth-616)/Members",
  "Avengers Unity Division (Earth-616)/Members",
  "Brotherhood of Evil Mutants (Earth-616)/Members",
  "Global Reaction Agency for Mysterious Paranormal Activity (Earth-616)/Members",
  "Genoshan Cabinet (Earth-616)/Members",
  "House of Agon (Earth-616)/Members",
  "Knights of Wundagore (Earth-616)/Members",
  "Mighty Avengers (Pym) (Earth-616)/Members",
  "Queen's Vengeance (Earth-398)/Members",
  "Romany (Earth-616)/Members",
  "Underground (Secret Empire) (Earth-616)/Members",
  "West Coast Avengers (Earth-616)/Members",
  "X-Factor (Government) (Earth-616)/Members",
  "X-Factor (Serval Industries) (Earth-616)/Members",
  "Serval Industries (Earth-616)/Members",
  "Single Characters",
  "Male Characters",
  "Height 6 ft. 0 in. (1.83 m)",
  "Weight 160-179 lbs (72.57-81.65 kg)",
  "Blue Eyes",
  "Silver Hair",
  "Humans (Homo sapiens)",
  "Mutants (Homo superior)",
  "Mutates",
  "Terrigenesis",
  "Living Characters",
  "Formerly Deceased",
  "Earth-616/Characters",
  "Killed by Michael Korvac (Earth-691)",
  "Killed by Max Eisenhardt (Earth-616)",
  "Public Identity Characters",
  "Multiple Citizenship",
  "Americans",
  "Serbs",
  "Adventurers",
  "Government Agents",
  "Terrorists",
  "Stan Lee/Creator",
  "Jack Kirby/Creator",
  "1964 Character Debuts",
  "Superhuman Speed",
  "Superhuman Reflexes",
  "Superhuman Agility",
  "Superhuman Durability",
  "Regeneration",
  "Superhuman Stamina",
  "Superhuman Strength",
  "Intangibility",
  "Time Traveling",
  "Temporal Duplication",
  "Pietro Maximoff (Earth-616)/Quotes",
  "Power Grid/Intelligence/Learned",
  "Power Grid/Strength/Superhuman (800 lbs-25 ton)",
  "Power Grid/Speed/Supersonic",
  "Power Grid/Durability/Enhanced",
  "Power Grid/Energy Projection/None",
  "Power Grid/Fighting Skills/Experienced Fighter",
  "Maximoff Family",
  "Twins",
  "Romani",
  "Time Travelers",
  "Trained by Captain America",
  "Depowered Terrigenesis-Mutates",
  "Separated Characters",
  "Korvac Saga participants",
  "Korvac Saga casualties",
  "High Evolutionary Experiment",
  "Collector's Museum",
  "Galactic Marathon participants",
  "Depression",
  "Sociopaths",
  "Floating Super-Hero Poker Game participants",
  "Instagram Users",
  "Genetically Engineered",
  "Multilingual",
  "Artificial Mutants",
  "Vibration Generation"
]
  },
  {
    title: "Scarlet Witch",
    categories: [
  "Characters",
  "Avengers (Earth-616)/Members",
  "Romany (Earth-616)/Members",
  "Strange Academy (Earth-616)/Members",
  "Avengers Unity Division (Earth-616)/Members",
  "Axis (Avengers) (Earth-616)/Members",
  "Lethal Legion (Heroes Reborn) (Earth-616)/Members",
  "Avengers (Heroes Reborn) (Earth-616)/Members",
  "Force Works (Earth-616)/Members",
  "Secret Defenders (Earth-616)/Members",
  "Brides of Set (Earth-616)/Members",
  "West Coast Avengers (Earth-616)/Members",
  "Lady Liberators (Earth-616)/Members",
  "Brotherhood of Evil Mutants (Earth-616)/Members",
  "Divorced Characters",
  "Female Characters",
  "Height 5 ft. 7 in. (1.7 m)",
  "Weight 120-139 lbs (54.43-63.5 kg)",
  "Green Eyes",
  "Red Eyes",
  "Auburn Hair",
  "Demons",
  "Humans (Homo sapiens)",
  "Hybrids",
  "Mutates",
  "Living Characters",
  "Formerly Deceased",
  "Earth-616/Characters",
  "Killed by Thanos (Earth-616)",
  "Killed by Max Eisenhardt (Earth-616)",
  "Killed by Griever at the End of All Things (Multiverse)",
  "Public Identity Characters",
  "Multiple Citizenship",
  "Americans",
  "Serbs",
  "Adventurers",
  "Teachers",
  "Magicians",
  "Stan Lee/Creator",
  "Jack Kirby/Creator",
  "1964 Character Debuts",
  "Probability Manipulation",
  "Reality Warping",
  "Extrasensory Perception",
  "Precognition",
  "Soul Manipulation",
  "Resurrection",
  "Telekinesis",
  "Flight",
  "Energy Manipulation",
  "Force Field",
  "Energy Construct Creation",
  "Power Manipulation",
  "Power Amplification",
  "Power Bestowal",
  "Power Absorption",
  "Power Negation",
  "Transmutation",
  "Environment Connection",
  "Biological Manipulation",
  "Plant Manipulation",
  "Precipitation Manipulation",
  "Telepathy",
  "Astral Projection",
  "Illusions",
  "Healing",
  "Invisibility",
  "Teleportation",
  "Interdimensional Teleportation",
  "Time Manipulation",
  "Superhuman Durability",
  "Magic Immunity",
  "Speakers of English",
  "Speakers of French",
  "Speakers of German",
  "Speakers of Greek",
  "Wanda Maximoff (Earth-616)/Quotes",
  "Power Grid/Intelligence/Learned",
  "Power Grid/Strength/Normal",
  "Power Grid/Speed/Normal",
  "Power Grid/Durability/Normal",
  "Power Grid/Energy Projection/Multiple Types",
  "Power Grid/Fighting Skills/Some Training",
  "Twins",
  "Trained by Captain America",
  "Vision Family",
  "Maximoff Family",
  "Korvac Saga participants",
  "Korvac Saga casualties",
  "High Evolutionary Experiment",
  "Collector's Museum",
  "Insanity",
  "Vegetarians",
  "Romani",
  "Sorcerer Supreme Candidates",
  "Floating Super-Hero Poker Game participants",
  "Genetically Engineered",
  "Serbians",
  "Gestalt Characters",
  "Multilingual",
  "Occultism",
  "Summoning",
  "Nexus Beings",
  "Artificial Mutants",
  "Lactose Intolerance",
  "Brood-infected",
  "Infinity Gauntlet (Event) casualties"
]
  },
  {
    title: "She-Hulk",
    categories: [
  "Characters",
  "Avengers Emergency Response Squad (Earth-616)/Members",
  "Book Law (Earth-616)/Members",
  "Punch Club (Earth-616)/Members",
  "Avengers (Earth-616)/Members",
  "Hive (Symbiotes) (Earth-616)/Members",
  "Empyre (Earth-616)/Members",
  "A-Force (Earth-616)/Members",
  "Law Offices of Jennifer Walters, PLLC (Earth-616)/Members",
  "Mighty Avengers (Cage) (Earth-616)/Members",
  "Future Foundation (Earth-616)/Members",
  "Fantastic Four (Earth-616)/Members",
  "Fearsome Four (Earth-616)/Members",
  "Defenders (Initiative) (Earth-616)/Members",
  "Hulk Family (Earth-616)/Members",
  "Lady Liberators (Earth-616)/Members",
  "Freeman Bonding Incorporated (Earth-616)/Members",
  "Goodman, Lieber, Kurtzberg & Holliway (Earth-616)/Members",
  "Hulkbusters (S.H.I.E.L.D.) (Earth-616)/Members",
  "Strategic Homeland Intervention, Enforcement and Logistics Division (Earth-616)/Members",
  "Defenders (Earth-616)/Members",
  "Heroes for Hire (Oracle Inc.) (Earth-616)/Members",
  "Queen's Vengeance (Earth-398)/Members",
  "Fantastic Force (Earth-616)/Members",
  "Brides of Set (Earth-616)/Members",
  "Hosts of Phoenix Force",
  "Hosts of Symbiotes",
  "Single Characters",
  "Female Characters",
  "Height 5 ft. 6 in. (1.68 m)",
  "Height 6 ft. 7 in. (2.01 m)",
  "Weight 140-159 lbs (63.5-72.57 kg)",
  "Weight 700-799 lbs (317.51-362.87 kg)",
  "Green Eyes",
  "Formerly Grey Eyes",
  "Formerly No Visible Irises or Pupils",
  "Formerly Red Eyes",
  "Formerly Yellow Eyeballs",
  "Brown Hair",
  "Green Hair",
  "Formerly Blond Hair",
  "Formerly Grey Hair",
  "Green Skin",
  "Formerly Grey Skin",
  "Formerly Red Skin",
  "Gamma Ray Exposure",
  "Humans (Homo sapiens)",
  "Mutates",
  "Living Characters",
  "Formerly Deceased",
  "Earth-616/Characters",
  "Killed by Victor von Doom (Earth-616)",
  "Killed by Thanos (Earth-616)",
  "Killed by Cotati",
  "Empyre casualties",
  "Public Identity Characters",
  "Americans",
  "Adventurers",
  "Lawyers",
  "Stan Lee/Creator",
  "John Buscema/Creator",
  "1979 Character Debuts",
  "Superhuman Strength",
  "Superhuman Leaping",
  "Superhuman Speed",
  "Superhuman Durability",
  "Superhuman Hearing",
  "Self-Resurrection",
  "Jennifer Walters (Earth-616)/Quotes",
  "Power Grid/Intelligence/Learned",
  "Power Grid/Strength/Incalculable",
  "Power Grid/Speed/Superhuman",
  "Power Grid/Durability/Superhuman",
  "Power Grid/Energy Projection/None",
  "Power Grid/Fighting Skills/Experienced Fighter",
  "Bulletproof",
  "Regeneration",
  "Toxic Immunity",
  "Banner Family",
  "Walters Family",
  "Jameson Family",
  "Medium Awareness",
  "Secret Wars (1984 Event) participants",
  "Secret Wars (1984 Event) casualties",
  "Beta Level Threats",
  "Omega Level Threats",
  "Full Security Clearance",
  "Regenerative Durability",
  "Gestalt Characters",
  "Harvard University Student",
  "Power Stone wielders",
  "Floating Super-Hero Poker Game participants",
  "Interdimensional Travelers",
  "Time Travelers",
  "Iron Fist",
  "Bounty Hunters",
  "Nanobots",
  "Zombiotes"
    ]
  },
  {
    title: "Shang Chi",
    categories: [
  "Characters",
  "Five Weapons Society (Earth-616)/Members",
  "Champions of the Five Weapons Society (Earth-616)/Members",
  "Thunderbolts (Revolution) (Earth-616)/Members",
  "Avengers Emergency Response Squad (Earth-616)/Members",
  "Celestial Order of the Si-Fan (Earth-616)/Members",
  "Triads (Earth-616)/Members",
  "MI5 (Earth-616)/Members",
  "MI6 (Earth-616)/Members",
  "Freelance Restorations (Earth-616)/Members",
  "Marvel Knights (Earth-616)/Members",
  "Heroes for Hire (Knight & Wing) (Earth-616)/Members",
  "Avengers (Earth-616)/Members",
  "New Avengers (A.I.M.) (Earth-616)/Members",
  "Advanced Idea Mechanics (Earth-616)/Members",
  "Protectors (Earth-616)/Members",
  "Underground (Secret Empire) (Earth-616)/Members",
  "Agents of Atlas (Earth-616)/Members",
  "Atlas Foundation (Earth-616)/Members",
  "Hosts of Phoenix Force",
  "Single Characters",
  "Male Characters",
  "Height 5 ft. 10 in. (1.78 m)",
  "Weight 160-179 lbs (72.57-81.65 kg)",
  "Brown Eyes",
  "Black Hair",
  "Humans (Homo sapiens)",
  "Living Characters",
  "Earth-616/Characters",
  "No Dual Identity Characters",
  "Multiple Citizenship",
  "Chinese",
  "Americans",
  "Assassins",
  "Vigilantes",
  "Adventurers",
  "Teachers",
  "Steve Englehart/Creator",
  "Jim Starlin/Creator",
  "1973 Character Debuts",
  "Regeneration",
  "Chi Manipulation",
  "Energy Manipulation",
  "Portal Creation",
  "Teleportation",
  "Buddhism",
  "Zheng Shang-Chi (Earth-616)/Quotes",
  "Power Grid/Intelligence/Learned",
  "Power Grid/Strength/Normal",
  "Power Grid/Speed/Normal",
  "Power Grid/Durability/Normal",
  "Power Grid/Energy Projection/None",
  "Power Grid/Fighting Skills/Master: All Forms of Combat",
  "Empowered by Ex Nihilo's Origin Bombs",
  "Zheng Family",
  "Weapons Expert",
  "Martial Arts",
  "Pym Particles",
  "Thrown Weapon Mastery",
  "Gymnasts",
  "Government Agents",
  "Shooting",
  "Fencing",
  "Archery",
  "Duplication",
  "Spider-Virus Victims",
  "Buddhist Characters",
  "Khan Dynasty"
]
  },
  {
    title: "Peter Parker",
    categories: [
  "Characters",
  "Rand Corporation (Earth-616)/Members",
  "Oscorp (Earth-616)/Members",
  "Threats and Menaces (Earth-616)/Members",
  "Daily Bugle (Front Line) (Earth-616)/Members",
  "Uncle Ben Foundation (Earth-616)/Members",
  "Parker Industries (Earth-616)/Members",
  "Horizon Labs (Earth-616)/Members",
  "Parker Technologies (Earth-11638)/Members",
  "Daily Bugle (The DB!) (Earth-616)/Members",
  "Daily Globe (Earth-616)/Members",
  "Tricorp (Earth-616)/Members",
  "Jotunheim Strikeforce (Earth-616)/Members",
  "New Fantastic Four (Earth-616)/Members",
  "Darkhold Defiled (Earth-616)/Members",
  "Kang Club (Multiverse)/Members",
  "Web-Warriors (Earth-001)/Members",
  "League of Realms (Earth-616)/Members",
  "Resistance (Earth-51838)/Members",
  "Inklings (Earth-616)/Members",
  "Avengers (Earth-616)/Members",
  "Avengers Unity Division (Earth-616)/Members",
  "X-Men (Earth-616)/Members",
  "Special Class (Earth-616)/Members",
  "Mighty Avengers (Cage) (Earth-616)/Members",
  "Future Foundation (Earth-616)/Members",
  "Heroes for Hire (Knight & Wing) (Earth-616)/Members",
  "New Avengers (Earth-616)/Members",
  "Fantastic Four (Earth-616)/Members",
  "Secret Avengers (Civil War) (Earth-616)/Members",
  "Outlaws (Earth-616)/Members",
  "Brooklyn Avengers (Earth-616)/Members",
  "Secret Defenders (Earth-616)/Members",
  "Galactic Alliance of Spider-Men (Earth-616)/Members",
  "Mighty (Earth-616)/Members",
  "Spider-Army (Multiverse)/Members",
  "Spider Society (Earth-616)/Members",
  "Frightful Four (Earth-616)/Members",
  "Inner Demons (Earth-616)/Members",
  "Triads (Earth-616)/Members",
  "Hosts of Venom Symbiote",
  "Hosts of Enigma Force",
  "Hosts of Mania Symbiote",
  "Single Characters",
  "Male Characters",
  "Height 5 ft. 10 in. (1.78 m)",
  "Weight 160-179 lbs (72.57-81.65 kg)",
  "Hazel Eyes",
  "Brown Hair",
  "Humans (Homo sapiens)",
  "Mutates",
  "Living Characters",
  "Formerly Deceased",
  "Earth-616/Characters",
  "Killed by Victor von Doom (Earth-616)",
  "Killed by Terraxia (Earth-616)",
  "Killed by Morlun (Earth-001)",
  "Killed by Otto Octavius (Earth-616)",
  "Killed by Wade Wilson (Earth-616)",
  "Killed by Gabriel Stacy (Earth-616)",
  "Killed by Progenitor (Celestial) (Multiverse)",
  "Killed by Gwendolyn Stacy (Earth-65)",
  "Killed by Venom (Symbiote) (Earth-65)",
  "Killed by Cyrios (Earth-616)",
  "Killed by Callix (Earth-616)",
  "Secret Wars (1984 Event) casualties",
  "Infinity Gauntlet (Event) casualties",
  "A.X.E.: Judgment Day casualties",
  "Secret Identity Characters",
  "Americans",
  "Vigilantes",
  "Body Guards",
  "Mechanics",
  "Adventurers",
  "Wrestlers",
  "Teachers",
  "Students",
  "Engineers",
  "Scientists",
  "Inventors",
  "Stan Lee/Creator",
  "Steve Ditko/Creator",
  "1962 Character Debuts",
  "Superhuman Strength",
  "Superhuman Speed",
  "Superhuman Agility",
  "Superhuman Reflexes",
  "Superhuman Stamina",
  "Superhuman Durability",
  "Superhuman Equilibrium",
  "Regeneration",
  "Danger Sense",
  "Entomopathy",
  "Organic Webbing",
  "Night Vision",
  "Speakers of English",
  "Speakers of Chinese",
  "Medium Awareness",
  "Wc spiderman",
  "Peter Parker (Earth-616)/Quotes",
  "Power Grid/Intelligence/Gifted",
  "Power Grid/Strength/Superhuman (800 lbs-25 ton)",
  "Power Grid/Speed/Superhuman",
  "Power Grid/Durability/Enhanced",
  "Power Grid/Energy Projection/None",
  "Power Grid/Fighting Skills/Experienced Fighter",
  "Twitter Users",
  "Shared body characters",
  "Web-Slinging",
  "Superhuman Leaping",
  "Toxic Immunity",
  "Human/Spider Hybrids",
  "Hybrids",
  "Parker Family",
  "Doctors",
  "Geneticists",
  "Robotics",
  "Chemists",
  "Physicists",
  "Former Vampires",
  "Power Level 8",
  "Doctor Octopus Experiment",
  "Radioactive Spider-Powered",
  "Spider-Verse participants",
  "Reilly Family",
  "Facebook Users",
  "Consciousness Transferred",
  "Time Travelers",
  "The Other receptacles",
  "Midtown High School Students",
  "Gymnasts",
  "Empire State University Student",
  "Acrobats",
  "Secret Wars (1984 Event) participants",
  "Leaders",
  "Armor Users",
  "Trained by Captain America",
  "Trained by Shang-Chi",
  "Interdimensional Travelers",
  "Multilingual",
  "Martial Arts",
  "Athletic Skills",
  "Businesspeople",
  "Shared Identities",
  "Secret Wars (2015 Event) participants",
  "Shared Identities: Successors",
  "Millionaires",
  "Magic-Based Mutates",
  "Totemic Avatars",
  "Watson Family",
  "Jean Grey School faculty",
  "Floating Super-Hero Poker Game participants",
  "Spider-Geddon participants",
  "Gamma Ray Exposure",
  "Strength Class 25",
  "Magicians",
  "Arthropod Form",
  "Former Werewolves",
  "Post-Traumatic Stress Disorder",
  "Libra (Astrological Sign)",
  "Atheist Characters",
  "Nanobots",
  "Billionaires"
]
  },
  {
    title: "Spider-Woman",
    categories: [
  "Characters",
  "West Coast Avengers (Earth-616)/Members",
  "Spider-Society (Multiverse)/Members",
  "Daughters of Liberty (Earth-616)/Members",
  "Order of the Web (Earth-616)/Members",
  "Strikeforce (Earth-616)/Members",
  "Superior Spider-Army (Earth-928)/Members",
  "Sentient World Observation and Response Department (Earth-616)/Members",
  "Secret Avengers (S.H.I.E.L.D.) (Earth-616)/Members",
  "New Avengers (A.I.M.) (Earth-616)/Members",
  "Advanced Idea Mechanics (Earth-616)/Members",
  "Avengers (Earth-616)/Members",
  "New Avengers (Earth-616)/Members",
  "Heroes for Hire (Knight & Wing) (Earth-616)/Members",
  "Hydra (Earth-616)/Members",
  "Spider Society (Earth-616)/Members",
  "Drew and McCabe Private Investigations (Earth-616)/Members",
  "Strategic Homeland Intervention, Enforcement and Logistics Division (Earth-616)/Members",
  "Lady Liberators (Earth-616)/Members",
  "Single Characters",
  "Female Characters",
  "Height 5 ft. 10 in. (1.78 m)",
  "Weight 120-139 lbs (54.43-63.5 kg)",
  "Green Eyes",
  "Formerly Blue Eyes",
  "Dyed Black Hair",
  "Formerly Brown Hair",
  "Humans (Homo sapiens)",
  "Mutates",
  "Living Characters",
  "Formerly Deceased",
  "Earth-616/Characters",
  "Killed by Rachel Summers (Earth-811)",
  "Killed by Peter Parker (Earth-90214)",
  "Public Identity Characters",
  "Multiple Citizenship",
  "British",
  "English",
  "Americans",
  "Bounty Hunters",
  "Vigilantes",
  "Body Guards",
  "Adventurers",
  "Government Agents",
  "Spies",
  "Terrorists",
  "Private Investigators",
  "Mercenaries",
  "Hunters",
  "Archie Goodwin/Creator",
  "Sal Buscema/Creator",
  "Jim Mooney/Creator",
  "Marie Severin/Creator",
  "1976 Character Debuts",
  "Wallcrawling",
  "Superhuman Strength",
  "Superhuman Speed",
  "Superhuman Stamina",
  "Superhuman Durability",
  "Superhuman Agility",
  "Superhuman Reflexes",
  "Superhuman Flexibility",
  "Superhuman Hearing",
  "Toxic Immunity",
  "Electricity Generation",
  "Regeneration",
  "Advanced Longevity",
  "Pheromones",
  "Winged Flight",
  "Martial Arts",
  "Acrobats",
  "Gymnasts",
  "Multilingual",
  "Speakers of English",
  "Speakers of Russian",
  "Speakers of Japanese",
  "Speakers of French",
  "Speakers of Spanish",
  "Speakers of Portuguese",
  "Speakers of Korean",
  "Speakers of German",
  "Allergies",
  "Jessica Drew (Earth-616)/Quotes",
  "Power Grid/Intelligence/Learned",
  "Power Grid/Strength/Superhuman (25-75 ton)",
  "Power Grid/Speed/Superhuman",
  "Power Grid/Durability/Regenerative",
  "Power Grid/Energy Projection/Single Type: Long Range",
  "Power Grid/Fighting Skills/Experienced Fighter",
  "Trained by Taskmaster",
  "Drew Family",
  "Human/Spider Hybrids",
  "S.H.I.E.L.D. Agents Level 7",
  "Power Level 8",
  "High Evolutionary Experiment",
  "Doctor Octopus Experiment",
  "Genetically Engineered",
  "Spider-Verse participants",
  "Spider-Geddon participants",
  "Interdimensional Travelers",
  "Instagram Users",
  "Totemic Avatars",
  "Hydra Experiment",
  "Sagittarius (Astrological Sign)",
  "Telepathic Immunity"
]
  },
  {
    title: "Eddie Brock",
    categories: [
  "Characters",
  "New Avengers (Winter Soldier) (Earth-616)/Members",
  "Hive (Symbiotes) (Earth-616)/Members",
  "Sinister Six (Earth-616)/Members",
  "Food, Emergency Aid, Shelter and Training (Earth-616)/Members",
  "Revengers (Earth-616)/Members",
  "Savage Six (Crime-Master) (Earth-616)/Members",
  "Anti-Symbiote Task Force (Earth-616)/Members",
  "Federal Bureau of Investigation (Earth-616)/Members",
  "Resistance (Venomverse) (Earth-22249)/Members",
  "Daily Globe (Earth-616)/Members",
  "Hosts of Extrembiote Symbiote",
  "Hosts of Tyrannosaurus Symbiote",
  "Hosts of Venom Symbiote",
  "Hosts of Anti-Venom Symbiote",
  "Hosts of Enigma Force",
  "Hosts of Sleeper Symbiote",
  "Hosts of Mania Symbiote",
  "Hosts of Carnage Symbiote",
  "Hosts of Toxin Symbiote",
  "Divorced Characters",
  "Male Characters",
  "Height 6 ft. 3 in. (1.91 m)",
  "Variable Height",
  "Weight 260-279 lbs (117.93-127.01 kg)",
  "Variable Weight",
  "Blue Eyes",
  "No Visible Irises or Pupils",
  "White Eyeballs",
  "Strawberry Blond Hair",
  "No Hair",
  "Claws",
  "Fangs",
  "Prehensile Tongue",
  "Tentacles",
  "Humans (Homo sapiens)",
  "Living Characters",
  "Formerly Deceased",
  "Earth-616/Characters",
  "Killed by Knull (Earth-616)",
  "King in Black casualties",
  "Secret Identity Characters",
  "Americans",
  "Vigilantes",
  "Deities",
  "Government Agents",
  "Reporters",
  "Kings in Black",
  "Monarchs",
  "Hunters",
  "David Michelinie/Creator",
  "Todd McFarlane/Creator",
  "1986 Character Debuts",
  "Mind Link",
  "Edward Brock (Earth-616)/Quotes",
  "Power Grid/Intelligence/Normal",
  "Power Grid/Strength/Superhuman (25-75 ton)",
  "Power Grid/Speed/Superhuman",
  "Power Grid/Durability/Bulletproof",
  "Power Grid/Energy Projection/None",
  "Power Grid/Fighting Skills/Normal",
  "Superhuman Stamina",
  "Wallcrawling",
  "Camouflage",
  "Fire Weakness",
  "Sonic Weakness",
  "Web-Slinging",
  "Writers",
  "Catholic Characters",
  "Cancer (disease)",
  "Cannibals",
  "Brock Family",
  "Superhuman Leaping",
  "Weapons Expert",
  "Shared Identities: Successors",
  "Regeneration",
  "Regenerative Durability",
  "Interdimensional Travelers",
  "Post-Traumatic Stress Disorder",
  "One Hand",
  "Object-Based Powers",
  "Apotheosized Mortals",
  "Time Travelers",
  "Time-Looped",
  "Permanently Bonded (Symbiotes)",
  "Time Traveling",
  "Chronoskimming",
  "Living Abyss",
  "Darkness Deities",
  "Former Deities",
  "Winged Flight"
]
  },
  {
    title: "Thanos",
    categories: [
  "Characters",
  "Infinity Watch (Earth-616)/Members",
  "Defenders (Thanos) (Earth-616)/Members",
  "Cabal (Namor) (Earth-616)/Members",
  "Masters of Evil (Multiverse)/Members",
  "Galactic Council (Earth-616)/Members",
  "Hosts of Venom Symbiote",
  "Single Characters",
  "Male Characters",
  "Height 6 ft. 7 in. (2.01 m)",
  "Weight 900-999 lbs (408.23-453.59 kg)",
  "Red Eyes",
  "No Hair",
  "Purple Skin",
  "Furrowed Chin",
  "Cyborgs",
  "Eternals (Homo immortalis)",
  "Mutant Eternals (Deviant Syndrome)",
  "Mutates",
  "Titans (Eternals)",
  "True Immortals",
  "Living Characters",
  "Formerly Deceased",
  "Earth-616/Characters",
  "Killed by Adam Warlock (Earth-616)",
  "Killed by Arthur Douglas (Earth-616)",
  "Killed by Victor von Doom (Earth-616)",
  "Killed by Gamora Zen Whoberi Ben Titan (Earth-7528)",
  "Killed by Druig (Earth-616)",
  "Killed by Phastos (Earth-616)",
  "No Dual Identity Characters",
  "Dynamo City citizens",
  "Multiple Citizenship",
  "Titanian Eternals",
  "Leaders",
  "Pirates",
  "Conquerors",
  "Farmers",
  "Monarchs",
  "Jim Starlin/Creator",
  "Mike Friedrich/Creator",
  "1972 Character Debuts",
  "Cosmic Awareness",
  "Superhuman Strength",
  "Superhuman Agility",
  "Superhuman Reflexes",
  "Superhuman Stamina",
  "Superhuman Speed",
  "Invulnerability",
  "Disease Immunity",
  "Regeneration",
  "Force Field",
  "Energy Manipulation",
  "Energy Projection",
  "Concussive Blasts",
  "Heat Generation",
  "Optic Blasts",
  "Power Amplification",
  "Telepathy",
  "Telepathic Immunity",
  "Matter Manipulation",
  "Transmutation",
  "Healing",
  "Telekinesis",
  "Magicians",
  "Self Sustenance",
  "Flight",
  "Teleportation",
  "Remote Teleportation",
  "Summoning",
  "Necromancy",
  "Martial Arts",
  "Fencing",
  "Robotics",
  "Thanos (Earth-616)/Quotes",
  "Power Grid/Intelligence/Super-Genius",
  "Power Grid/Strength/Incalculable",
  "Power Grid/Speed/Superhuman",
  "Power Grid/Speed/Warp",
  "Power Grid/Durability/Superhuman",
  "Power Grid/Energy Projection/Multiple Types",
  "Power Grid/Fighting Skills/Experienced Fighter",
  "Strength Class 100",
  "Post-M-Day Mutants (Non-Human)",
  "Magic-Based Mutates",
  "Genetically Engineered",
  "Warlords",
  "Apotheosized Mortals",
  "Former Deities",
  "Interdimensional Travelers",
  "Cosmic Cube Enhanced",
  "Thanos Family",
  "Kronos Dynasty",
  "Secret Wars (2015 Event) participants",
  "Category 1 Life Enders",
  "Universal Threat Level",
  "Cosmic Level Threats",
  "Infinity Gauntlet wielders",
  "Avatars of Death",
  "Time Travelers",
  "DC Comics Pastiches"
    ]
  }
];

const article = articles[Math.floor(Math.random() * articles.length)];

const categoriesDiv = document.getElementById("categories");

categoriesDiv.textContent = article.categories.join(" | ");

const guessBtn = document.getElementById("guessBtn");
const guessInput = document.getElementById("guessInput");
const feedback = document.getElementById("feedback");

guessBtn.addEventListener("click", () => {
  const guess = guessInput.value.trim().toLowerCase();
  const answer = article.title.toLowerCase();

  if (guess === answer) {
    feedback.textContent = "good job!";
  } else {
    feedback.textContent = "sorry, the answer was: " + article.title;
  }

  guessInput.value = "";
});



