const articles = [
  {
    title: "Steve Rogers",
    categories: [
  "Characters",
  "Avengers Emergency Response Squad (Earth-616)/Members",
  "Avengers Unity Division (Earth-616)/Members",
  "Avengers (Earth-616)/Members",
  "Strategic Homeland Intervention, Enforcement and Logistics Division (Earth-616)/Members",
  "Illuminati (Earth-616)/Members",
  "Invaders (Earth-616)/Members",
  "United States Army (Earth-616)/Members",
  "Project Rebirth (Earth-616)/Members",
  "Secret Avengers (Black Ops Unit) (Earth-616)/Members",
  "Mighty (Earth-616)/Members",
  "Captain America Corps (Earth-616)/Members",
  "Secret Avengers (Civil War) (Earth-616)/Members",
  "New Avengers (Earth-616)/Members",
  "Avengers (Multiverse)/Members",
  "Avengers (Heroes Reborn) (Earth-616)/Members",
  "Secret Defenders (Earth-616)/Members",
  "Specialized Unit, Enhanced Soldiers (Earth-616)/Members",
  "Hive (Symbiotes) (Earth-616)/Members",
  "Jotunheim Strikeforce (Earth-616)/Members",
  "Queen's Vengeance (Earth-398)/Members",
  "Hosts of Carnage Symbiote",
  "Single Characters",
  "Male Characters",
  "Height 6 ft. 2 in. (1.88 m)",
  "Weight 220-239 lbs (99.79-108.86 kg)",
  "Blue Eyes",
  "Blond Hair",
  "Humans (Homo sapiens)",
  "Mutates",
  "Super-Soldiers",
  "Living Characters",
  "Formerly Deceased",
  "Earth-616/Characters",
  "Killed by Victor von Doom (Earth-616)",
  "Killed by Thanos (Earth-616)",
  "Killed by Michael Korvac (Earth-691)",
  "Killed by Nathaniel Richards (Kang) (Earth-6311)",
  "Killed by Sharon Carter (Earth-616)",
  "Killed by Progenitor (Celestial) (Multiverse)",
  "Secret Wars (1984 Event) casualties",
  "Infinity Gauntlet (Event) casualties",
  "Korvac Saga casualties",
  "Civil War casualties",
  "Time Runs Out casualties",
  "A.X.E.: Judgment Day casualties",
  "Public Identity Characters",
  "Americans",
  "Leaders",
  "Police Officers",
  "Adventurers",
  "Teachers",
  "Military Personnel",
  "Joe Simon/Creator",
  "Jack Kirby/Creator",
  "1940 Character Debuts",
  "Disease Immunity",
  "Regeneration",
  "Artificially Enhanced Intelligence",
  "Advanced Longevity",
  "Superhuman Strength",
  "Superhuman Stamina",
  "Superhuman Agility",
  "Superhuman Reflexes",
  "Superhuman Speed",
  "Superhuman Senses",
  "Superhuman Durability",
  "Wallcrawling",
  "Organic Webbing",
  "Strategists",
  "Martial Arts",
  "Shield Fighting",
  "Acrobats",
  "Gymnasts",
  "Shooting",
  "Fencing",
  "Weapons Expert",
  "Thrown Weapon Mastery",
  "Computer Hacking Skills",
  "Pilots",
  "Multilingual",
  "Speakers of English",
  "Speakers of Spanish",
  "Speakers of Japanese",
  "Speakers of German",
  "Speakers of Russian",
  "Speakers of French",
  "Speakers of Italian",
  "Steven Rogers (Earth-616)/Quotes",
  "Power Grid/Intelligence/Learned",
  "Power Grid/Strength/Peak Human",
  "Power Grid/Speed/Normal",
  "Power Grid/Durability/Enhanced",
  "Power Grid/Energy Projection/None",
  "Power Grid/Fighting Skills/Master: Several Forms of Combat",
  "Worthy of Mjolnir",
  "WWII Characters",
  "Rogers Family",
  "Painters",
  "Abraham Erskine Experiment",
  "Power Level 8",
  "Doctor Octopus Experiment",
  "Secret Wars (1984 Event) participants",
  "Time Travelers",
  "Korvac Saga participants",
  "Government Agents",
  "Destiny War Participants",
  "Paladin-Plus Clearance",
  "Time-Looped",
  "Spider-Virus Victims",
  "Collector's Museum",
  "S.H.I.E.L.D. Directors",
  "Shared Identities: Successors",
  "Ebony Blade User",
  "Infinity Gauntlet wielders",
  "Floating Super-Hero Poker Game participants",
  "Damnation participants",
  "Reincarnation",
  "Lupine Form",
  "Gestalt Characters",
  "Former Werewolves",
  "Libra (Astrological Sign)"
    ]
  },
  {
    title: "Tony Stark",
    categories: [
  "Characters",
  "Avengers (Earth-616)/Members",
  "West Coast Avengers (Earth-616)/Members",
  "Hellfire Club (Earth-616)/Members",
  "Alcoholics Anonymous (Earth-616)/Members",
  "Space Friends (Earth-616)/Members",
  "Darkhold Defiled (Earth-616)/Members",
  "A.I. Army (Earth-616)/Members",
  "Stark Unlimited (Earth-616)/Members",
  "Stark Industries (Earth-616)/Members",
  "Red Team (Earth-15513)/Members",
  "Avengers (Heroes Reborn) (Earth-616)/Members",
  "Illuminati (Earth-616)/Members",
  "Axis (Avengers) (Earth-616)/Members",
  "Stark Resilient (Earth-616)/Members",
  "Strategic Homeland Intervention, Enforcement and Logistics Division (Earth-616)/Members",
  "Guardians of the Galaxy (Earth-616)/Members",
  "50-State Initiative (Earth-616)/Members",
  "New Avengers (Earth-616)/Members",
  "Mighty Avengers (Initiative) (Earth-616)/Members",
  "Mighty Avengers (Pym) (Earth-616)/Members",
  "Maria Stark Foundation (Earth-616)/Members",
  "Stark Solutions (Earth-616)/Members",
  "Force Works (Earth-616)/Members",
  "United States Department of Defense (Earth-616)/Members",
  "Mighty (Earth-616)/Members",
  "Knights of the Atomic Round Table (Earth-616)/Members",
  "Damage Control (Earth-616)/Members",
  "Imperio Techworks (Earth-616)/Members",
  "Queen's Vengeance (Earth-398)/Members",
  "Hosts of Extrembiote Symbiote",
  "Single Characters",
  "Male Characters",
  "Height 6 ft. 1 in. (1.85 m)",
  "Height 6 ft. 6 in. (1.98 m)",
  "Weight 220-239 lbs (99.79-108.86 kg)",
  "Weight 400-499 lbs (181.44-226.8 kg)",
  "Blue Eyes",
  "Black Hair",
  "Cyborgs",
  "Humans (Homo sapiens)",
  "Living Characters",
  "Formerly Deceased",
  "Earth-616/Characters",
  "Killed by En Dwi Gast (Earth-616)",
  "Killed by Terraxia (Earth-616)",
  "Killed by Nathaniel Richards (Kang) (Earth-6311)",
  "Infinity Gauntlet (Event) casualties",
  "Crossing casualties",
  "Time Runs Out casualties",
  "Self-sacrifice",
  "Public Identity Characters",
  "Multiple Citizenship",
  "Americans",
  "Bulgarians",
  "Businesspeople",
  "Mechanics",
  "Adventurers",
  "Secretaries",
  "Engineers",
  "Inventors",
  "Stan Lee/Creator",
  "Larry Lieber/Creator",
  "Don Heck/Creator",
  "Jack Kirby/Creator",
  "1962 Character Debuts",
  "Speakers of English",
  "Speakers of Japanese",
  "Speakers of Chinese",
  "Speakers of Spanish",
  "Speakers of French",
  "Speakers of Russian",
  "Speakers of Korean",
  "Speakers of Urdu",
  "Anthony Stark (Earth-616)/Quotes",
  "Power Grid/Intelligence/Super-Genius",
  "Power Grid/Strength/Normal",
  "Power Grid/Strength/Superhuman (75-100 ton)",
  "Power Grid/Speed/Normal",
  "Power Grid/Speed/Supersonic",
  "Power Grid/Durability/Weak",
  "Power Grid/Durability/Superhuman",
  "Power Grid/Energy Projection/None",
  "Power Grid/Energy Projection/Multiple Types",
  "Power Grid/Fighting Skills/Experienced Fighter",
  "Alcoholism",
  "Armor Users",
  "Artificial Intelligences",
  "Artificially Enhanced Intelligence",
  "Atheist Characters",
  "Blood Type A+",
  "Cambridge University Student",
  "Collector's Museum",
  "Computer Hacking Skills",
  "Concussive Blasts",
  "Consciousness Transferred",
  "Death by accident",
  "Depression",
  "Doctor Octopus Experiment",
  "Extremis",
  "Fear Itself",
  "Flight",
  "Floating Super-Hero Poker Game participants",
  "Gemini (Astrological Sign)",
  "Gestalt Characters",
  "Infinity Gauntlet wielders",
  "Interdimensional Travelers",
  "Korvac Saga participants",
  "M.I.T. Student",
  "Millionaires",
  "Multilingual",
  "Multiple forms of Energy Projection",
  "Physicists",
  "Plasma Generation",
  "Power Level 9",
  "Regeneration",
  "Robotics",
  "S.H.I.E.L.D. Directors",
  "Scientists",
  "Shared Identities: Successors",
  "Stark Family",
  "Strength Class 100",
  "Super-Genius Intelligence",
  "Superhuman (75-100 ton) Strength",
  "Superhuman Durability",
  "Superhuman Strength",
  "Supersonic Speed",
  "Technopaths",
  "Doctors",
  "Three Doctorates",
  "Time Travelers",
  "Trained by Captain America",
  "Trained by Shang-Chi",
  "Vietnam War Characters",
  "Virtual Reality Users",
  "Warp Speed",
  "Leaders",
  "Nanobots",
  "Power Cosmic",
  "Billionaires",
  "Martial Arts"
    ]
  },
 {
    title: "Captain Marvel",
categories = [
  "Characters",
  "Killed by Michael Rossi (Earth-616)",
  "Killed by Progenitor (Celestial) (Multiverse)",
  "Killed by Thanos (Earth-616)",
  "A.X.E.: Judgment Day casualties",
  "Public Identity Characters",
  "Americans",
  "Intelligence Agents",
  "Leaders",
  "Military Personnel",
  "Adventurers",
  "Writers",
  "Pilots",
  "Roy Thomas/Creator",
  "Gene Colan/Creator",
  "1967 Character Debuts",
  "Flight",
  "Danger Sense",
  "Superhuman Strength",
  "Superhuman Durability",
  "Superhuman Stamina",
  "Superhuman Agility",
  "Superhuman Reflexes",
  "Healing",
  "Energy Absorption",
  "Energy Manipulation",
  "Light Generation",
  "Self Sustenance",
  "Size Increase",
  "Regeneration",
  "Speakers of English",
  "Speakers of Russian",
  "Speakers of Chinese",
  "Speakers of Arabic",
  "Speakers of French",
  "Carol Danvers (Earth-616)/Quotes",
  "Power Grid/Intelligence/Learned",
  "Power Grid/Strength/Superhuman (25-75 ton)",
  "Power Grid/Speed/Supersonic",
  "Power Grid/Durability/Superhuman",
  "Power Grid/Energy Projection/Single Type: Long Range",
  "Power Grid/Fighting Skills/Experienced Fighter",
  "Government Agents",
  "Human/Kree Hybrids",
  "Psyche-Magnitron Enhanced",
  "Kree Experiment",
  "Danvers Family",
  "Strength Class 50",
  "Strength Class 90",
  "Strength Class 100",
  "Alcoholism",
  "Multilingual",
  "Power Level 8",
  "Avengers Clearance Alpha",
  "Korvac Saga participants",
  "Astronauts",
  "Secret Wars (2015 Event) participants",
  "War in Afghanistan Characters",
  "Interdimensional Travelers",
  "Floating Super-Hero Poker Game participants",
  "Damnation participants",
  "Reality Stone wielders",
  "Consciousness Transferred",
  "Gestalt Characters",
  "Optic Blasts",
  "Cancer (disease)",
  "Brood-infected"
]
  },
  {
    title: "Thor",
 categories = [
  "Characters",
  "Thor Corps (Earth-616)/Members",
  "Avengers (Earth-616)/Members",
  "Heralds of Galactus (Earth-616)/Members",
  "Avengers (Hydra) (Earth-616)/Members",
  "Thor Corps (Earth-15513)/Members",
  "New Avengers (A.I.M.) (Earth-616)/Members",
  "Avengers Unity Division (Earth-616)/Members",
  "Axis (Avengers) (Earth-616)/Members",
  "Avengers (Heroes Reborn) (Earth-616)/Members",
  "Avengers (1,000 AD) (Earth-616)/Members",
  "League of Realms (Earth-616)/Members",
  "God Squad (Earth-616)/Members",
  "Council of Godheads (Earth-616)/Members",
  "Queen's Vengeance (Earth-398)/Members",
  "Circus of Crime (Earth-616)/Members",
  "Godpack (Earth-616)/Members",
  "Hosts of All-Black Symbiote",
  "Single Characters",
  "Male Characters",
  "Height 6 ft. 6 in. (1.98 m)",
  "Height 5 ft. 9 in. (1.75 m)",
  "Weight 600-699 lbs (272.16-317.51 kg)",
  "Weight 140-159 lbs (63.5-72.57 kg)",
  "Blue Eyes",
  "Formerly No Visible Irises or Pupils",
  "Formerly Yellow Eyes",
  "Formerly White Eyeballs",
  "Formerly Green Eyeballs",
  "Blond Hair",
  "Formerly White Hair",
  "Formerly Blue Skin",
  "Formerly Green Skin",
  "Claws",
  "Cathexis Ray Exposure",
  "Asgardians",
  "Deities",
  "Elder Gods",
  "Gamma Ray Exposure",
  "Humans (Homo sapiens)",
  "Mutates",
  "Virtual Immortals",
  "Living Characters",
  "Formerly Deceased",
  "Earth-616/Characters",
  "Killed by Victor von Doom (Earth-616)",
  "Killed by Laufey (Earth-616)",
  "Killed by En Dwi Gast (Earth-616)",
  "Killed by Cul Borson (Earth-616)",
  "Killed by All-Black (Symbiote) (Earth-616)",
  "Killed by Progenitor (Celestial) (Multiverse)",
  "Killed by Thanos (Earth-616)",
  "Killed by Loki Laufeyson (Ikol) (Earth-616)",
  "Secret Wars (1984 Event) casualties",
  "Fear Itself casualties",
  "Time Runs Out casualties",
  "A.X.E.: Judgment Day casualties",
  "No Dual Identity Characters",
  "Sky Fathers",
  "Monarchs",
  "Physicians",
  "Adventurers",
  "Construction worker",
  "Don Rico/Creator",
  "Hy Rosen/Creator",
  "Stan Lee/Creator",
  "Jack Kirby/Creator",
  "Larry Lieber/Creator",
  "1950 Character Debuts",
  "Elder God/Asgardian Hybrids",
  "Superhuman Strength",
  "Invulnerability",
  "Disease Immunity",
  "Toxic Immunity",
  "Cold Immunity",
  "Superhuman Speed",
  "Superhuman Stamina",
  "Superhuman Agility",
  "Superhuman Reflexes",
  "Energy Manipulation",
  "Energy Projection",
  "Weather Manipulation",
  "Thunder Deities",
  "Precipitation Manipulation",
  "Wind Manipulation",
  "Electricity Manipulation",
  "Water Manipulation",
  "Ice Manipulation",
  "Electricity Generation",
  "Superhuman Senses",
  "Superhuman Vision",
  "Superhuman Hearing",
  "Regeneration",
  "Wind Breath",
  "Flight",
  "Telepathy",
  "Teleportation",
  "Force Field",
  "Portal Creation",
  "Time Manipulation",
  "Healing",
  "Power Absorption",
  "Fire Generation",
  "Fire Manipulation",
  "Geokinesis",
  "Magicians",
  "Precognition",
  "Power Cosmic",
  "Plant Manipulation",
  "Telepathic Immunity",
  "Energy Absorption",
  "Magnetism Manipulation",
  "Matter Manipulation",
  "Transmutation",
  "Electromagnetic Spectrum Manipulation",
  "Energy Senses",
  "Interdimensional Teleportation",
  "Remote Teleportation",
  "Soul Manipulation",
  "Life-Force Absorption",
  "Time Traveling",
  "Resurrection",
  "1962 Character Debuts",
  "Thor Odinson (Earth-616)/Quotes",
  "Power Grid/Intelligence/Normal",
  "Power Grid/Strength/Incalculable",
  "Power Grid/Speed/Warp",
  "Power Grid/Durability/Superhuman",
  "Power Grid/Energy Projection/Multiple Types",
  "Power Grid/Fighting Skills/Experienced Fighter",
  "Worthy of Mjolnir",
  "Fencing",
  "One Arm",
  "One Eye",
  "Doctor Octopus Experiment",
  "Secret Wars (1984 Event) participants",
  "Korvac Saga participants",
  "Time Travelers",
  "Interdimensional Travelers",
  "Diplomatic Immunity",
  "Dynamokinesis",
  "Collector's Museum",
  "Gaea Family",
  "Thor Family",
  "Odin Family",
  "Frigga Family",
  "Trojan War Characters",
  "Secret Wars (2015 Event) participants",
  "Power Stone wielders",
  "Time Stone wielders",
  "Mythological Figures",
  "Brood-infected",
  "Avatar Form",
  "Gestalt Characters",
  "Characters Displaced to Earth-15513",
  "Strategists",
  "Dimensional Rulers",
  "Messiahs",
  "Billionaires",
  "Lightning Deities",
  "Storm Deities",
  "Asgard Monarchs",
  "Former Deities",
  "Erased History"
]
  },
  {
    title: "Black Panther",
    categories: [
  "Characters",
  "Avengers (Earth-616)/Members",
  "Taifa Ngao (Earth-616)/Members",
  "Panther Cult (Earth-616)/Members",
  "Congress of Worlds (Earth-616)/Members",
  "Maroons (Earth-616)/Members",
  "Galactic Union (Earth-616)/Members",
  "Structure (Vampires) (Earth-616)/Members",
  "Crew (Earth-616)/Members",
  "Ultimates (Earth-616)/Members",
  "Nameless (Intergalactic Empire of Wakanda) (Earth-616)/Members",
  "Alpha Flight's Board of Governors (Earth-616)/Members",
  "Illuminati (Earth-616)/Members",
  "Fantastic Four (Earth-616)/Members",
  "Fantastic Force (Earth-616)/Members",
  "Defenders (Earth-616)/Members",
  "Secret Avengers (Civil War) (Earth-616)/Members",
  "Queen's Vengeance (Earth-398)/Members",
  "Hosts of Phoenix Force",
  "Hosts of Spirits of Vengeance",
  "Hosts of Shadow King",
  "Hosts of Varnae",
  "Single Characters",
  "Male Characters",
  "Height 6 ft. 0 in. (1.83 m)",
  "Weight 200-219 lbs (90.72-99.79 kg)",
  "Brown Eyes",
  "Amber Eyes",
  "Green Eyes",
  "Black Hair",
  "Claws",
  "Humans (Homo sapiens)",
  "Mutates",
  "Living Characters",
  "Formerly Deceased",
  "Earth-616/Characters",
  "Killed by Michael Korvac (Earth-691)",
  "Korvac Saga casualties",
  "Public Identity Characters",
  "Wakandans",
  "Vigilantes",
  "Monarchs",
  "Adventurers",
  "Teachers",
  "Scientists",
  "Stan Lee/Creator",
  "Jack Kirby/Creator",
  "1966 Character Debuts",
  "Superhuman Senses",
  "Telescopic Vision",
  "Ultraviolet Vision",
  "Infrared Vision",
  "Night Vision",
  "Superhuman Hearing",
  "Superhuman Smelling",
  "Superhuman Taste",
  "Necromancy",
  "Energy Construct Creation",
  "Cosmic Awareness",
  "Clairvoyance",
  "Martial Arts",
  "Acrobats",
  "Gymnasts",
  "Shooting",
  "Strategists",
  "Trackers",
  "Multilingual",
  "Inventors",
  "Engineers",
  "Invisibility",
  "Teleportation",
  "T'Challa (Earth-616)/Quotes",
  "Power Grid/Intelligence/Genius",
  "Power Grid/Strength/Peak Human",
  "Power Grid/Speed/Normal",
  "Power Grid/Durability/Enhanced",
  "Power Grid/Energy Projection/Single Type: Short Range",
  "Power Grid/Fighting Skills/Master: Single Form of Combat",
  "Vertical Pupils",
  "Object-Based Powers",
  "Wakandan Royal Family",
  "Munroe Family",
  "Leaders",
  "Ebony Blade User",
  "Weapons Expert",
  "Heart-Shaped Herb",
  "Chemists",
  "Physicists",
  "Robotics",
  "Millionaires",
  "Time Travelers",
  "Korvac Saga participants",
  "Diplomatic Immunity",
  "Oxford University Student",
  "Spider-Virus Victims",
  "Collector's Museum",
  "Armor Users",
  "Secret Wars (2015 Event) participants",
  "Totemic Avatars",
  "Infinity Gauntlet wielders",
  "Damnation participants",
  "Regeneration",
  "Interdimensional Travelers",
  "Souls Sold to Mephisto",
  "Slaves",
  "Fencing",
  "Worthy of Mjolnir",
  "Super-Genius Intelligence",
  "Shadow King",
  "Former Vampires",
  "Billionaires"
    ]
  },
  {
    title: "Vision",
    categories: [
  "Characters",
  "Avengers (Earth-616)/Members",
  "Avengers (Hydra) (Earth-616)/Members",
  "Avengers Unity Division (Earth-616)/Members",
  "Avengers Artificial Intelligence Squad (Earth-616)/Members",
  "Queen's Vengeance (Earth-398)/Members",
  "Avengers (Heroes Reborn) (Earth-616)/Members",
  "West Coast Avengers (Earth-616)/Members",
  "Divorced Characters",
  "Male Characters",
  "Height 6 ft. 3 in. (1.91 m)",
  "Weight 300-399 lbs (136.08-181.44 kg)",
  "Variable Weight",
  "Gold Eyes",
  "No Hair",
  "Red Skin",
  "Cyborgs",
  "Synthezoids",
  "Living Characters",
  "Formerly Deceased",
  "Earth-616/Characters",
  "Killed by Thanos (Earth-616)",
  "Killed by Jennifer Walters (Earth-616)",
  "Killed by Bruce Banner (Earth-616)",
  "Killed by Eric Williams (Earth-616)",
  "Avengers Disassembled casualties",
  "No Dual Identity Characters",
  "Americans",
  "Adventurers",
  "Roy Thomas/Creator",
  "John Buscema/Creator",
  "1968 Character Debuts",
  "Technopaths",
  "Nanobots",
  "Appearance Alteration",
  "Superhuman Hearing",
  "Superhuman Reflexes",
  "Superhuman Stamina",
  "Density Manipulation",
  "Intangibility",
  "Disruption",
  "Possession",
  "Invisibility",
  "Flight",
  "Superhuman Strength",
  "Superhuman Durability",
  "Energy Absorption",
  "Heat Generation",
  "Concussive Blasts",
  "Infrared Generation",
  "Microwave Generation",
  "Janet Van Dyne (Earth-616)/Quotes",
  "Power Grid/Intelligence/Gifted",
  "Power Grid/Strength/Superhuman (25-75 ton)",
  "Power Grid/Speed/Superhuman",
  "Power Grid/Durability/Superhuman",
  "Power Grid/Energy Projection/Multiple Types",
  "Power Grid/Fighting Skills/Some Training",
  "Pym Family",
  "Ultron Family",
  "Vision Family",
  "Maximoff Family",
  "Phineas Horton Experiment",
  "Horton Cells",
  "Artificial Intelligences",
  "Time Travelers",
  "Korvac Saga participants",
  "Korvac Saga casualties",
  "Metal Body",
  "Gestalt Characters",
  "Pym Particles",
  "Infinity Gauntlet (Event) casualties"
    ]
  },
  {
    title: "Black Widow",
    categories: [
  "Advanced Idea Mechanics (Earth-616)/Members",
  "Underground (Secret Empire) (Earth-616)/Members",
  "Red Room (Secret Empire) (Earth-616)/Members",
  "Queen's Vengeance (Earth-398)/Members",
  "Hosts of Sliver Symbiote",
  "Divorced Characters",
  "Female Characters",
  "Height 5 ft. 7 in. (1.7 m)",
  "Weight 120-139 lbs (54.43-63.5 kg)",
  "Green Eyes",
  "Red Hair",
  "Formerly Black Hair",
  "Humans (Homo sapiens)",
  "Mutates",
  "Super-Soldiers",
  "Living Characters",
  "Formerly Deceased",
  "Earth-616/Characters",
  "Killed by Steven Rogers (Earth-61311)",
  "Korvac Saga casualties",
  "Secret Empire (Event) casualties",
  "Self-sacrifice",
  "Public Identity Characters",
  "Multiple Citizenship",
  "Russians",
  "Soviets",
  "Americans",
  "Ballet Dancers",
  "Assassins",
  "Adventurers",
  "Teachers",
  "Fashion Designers",
  "Mercenaries",
  "Stan Lee/Creator",
  "Don Rico/Creator",
  "Don Heck/Creator",
  "1964 Character Debuts",
  "Web-Slinging",
  "Wallcrawling",
  "Memory Absorption",
  "Speakers of Russian",
  "Speakers of English",
  "Speakers of French",
  "Speakers of German",
  "Speakers of Chinese",
  "Speakers of Japanese",
  "Wc fortnite",
  "Natalia Romanova (Earth-616)/Quotes",
  "Power Grid/Intelligence/Learned",
  "Power Grid/Strength/Peak Human",
  "Power Grid/Speed/Normal",
  "Power Grid/Durability/Enhanced",
  "Power Grid/Energy Projection/Single Type: Short Range",
  "Power Grid/Fighting Skills/Master: Several Forms of Combat",
  "Acrobats",
  "Advanced Longevity",
  "Athletic Skills",
  "Computer Hacking Skills",
  "Dancers",
  "Espionage",
  "Fighting Ability - Master of several forms of combat",
  "Government Agents",
  "Gymnasts",
  "Korvac Saga participants",
  "Martial Arts",
  "Multilingual",
  "Orthodox Characters",
  "Peak Human Strength",
  "Power Level 7",
  "Regeneration",
  "Romanov Family",
  "S.H.I.E.L.D. Agents Level 10",
  "Shield Fighting",
  "Shooting",
  "Space Stone wielders",
  "Spies",
  "Strategists",
  "Thrown Weapon Mastery",
  "Trained by Wolverine",
  "Weapons Expert",
  "Disease Immunity"
]
  },
  {
    title: "Peter Quill",
    categories: [
  "Characters",
  "Galactic Union (Earth-616)/Members",
  "Guardians of the Galaxy (Earth-616)/Members",
  "Imperial Kree Army (Earth-616)/Members",
  "Infinity Watch (Earth-616)/Members",
  "National Aeronautics and Space Administration (Earth-616)/Members",
  "Ravagers (Earth-616)/Members",
  "Imperial Guard (Earth-616)/Members",
  "United Front (Earth-616)/Members",
  "Swingin' Stevie Rogers' Band (Earth-61610)/Members",
  "Nova Corps (Earth-616)/Members",
  "Hosts of Symbiotes",
  "Separated Characters",
  "Male Characters",
  "Height 6 ft. 2 in. (1.88 m)",
  "Weight 160-179 lbs (72.57-81.65 kg)",
  "Blue Eyes",
  "Blond Hair",
  "Tattoos",
  "Human/Spartoi Hybrids",
  "Cyborgs",
  "Humans (Homo sapiens)",
  "Hybrids",
  "Spartoi",
  "Living Characters",
  "Formerly Deceased",
  "Earth-616/Characters",
  "Killed by Gamora Zen Whoberi Ben Titan (Earth-7528)",
  "Killed by Groot (Earth-616)",
  "Public Identity Characters",
  "Multiple Citizenship",
  "Americans",
  "Spartax Empire citizens",
  "Vigilantes",
  "Monarchs",
  "Adventurers",
  "Keith Giffen/Creator",
  "Ron Lim/Creator",
  "2004 Character Debuts",
  "Advanced Longevity",
  "Superhuman Durability",
  "Superhuman Reflexes",
  "Regeneration",
  "Apotheosized Mortals",
  "Sun Deities",
  "Gravitational Flight",
  "Light Generation",
  "Telepathic Immunity",
  "Cosmic Awareness",
  "Shooting",
  "Martial Arts",
  "Strategists",
  "Pilots",
  "Peter Quill (Earth-616)/Quotes",
  "Power Grid/Intelligence/Gifted",
  "Power Grid/Strength/Peak Human",
  "Power Grid/Speed/Normal",
  "Power Grid/Durability/Enhanced",
  "Power Grid/Energy Projection/None",
  "Power Grid/Fighting Skills/Experienced Fighter",
  "Quill Family",
  "Bisexual Characters",
  "Astronauts",
  "Leaders",
  "Thieves",
  "Interdimensional Travelers",
  "Secret Wars (2015 Event) participants",
  "Former Deities"
]
  }
];

const article = articles[Math.floor(Math.random() * articles.length)];

const categoriesDiv = document.getElementById("categories");

categoriesDiv.textContent = article.categories.join(" | ");

const guessBtn = document.getElementById("guessBtn");
const guessInput = document.getElementById("guessInput");
const feedback = document.getElementById("feedback");

guessBtn.addEventListener("click", () => {
  const guess = guessInput.value.trim().toLowerCase();
  const answer = article.title.toLowerCase();

  if (guess === answer) {
    feedback.textContent = "good job!";
  } else {
    feedback.textContent = "sorry, the answer was: " + article.title;
  }

  guessInput.value = "";
});


